#!/usr/bin/env python3
"""Preview/apply only Jev's section, six skills and guide to an existing Border.

No identity rewrite, member list changes, broad skill deployment, or MCP config
changes. Restore refuses to overwrite anything changed since this adoption.
"""
import argparse
import base64
from datetime import datetime, timezone
import difflib
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import stat
import sys
import uuid

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- netclaw-jev-advisor:start -->'
END = '<!-- netclaw-jev-advisor:end -->'
SKILLS = ('jev-evidence-review', 'jev-specialist-advice', 'jev-answer-review',
          'jev-diagnostic-advice', 'jev-change-review', 'jev-incident-triage')
ALLOWED = {'SOUL.md', '../docs/JEV-SCIENCE-OFFICER.md', 'docs/JEV-SCIENCE-OFFICER.md'} | {f'skills/{name}/SKILL.md' for name in SKILLS}


def module(name, filename):
    spec = importlib.util.spec_from_file_location(name, ROOT/'scripts'/filename)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


writer = module('jev_adopt_writer', 'write-env.py')
border = module('jev_border_persona', 'in2n-border-workspace.py')


def digest(data):
    return hashlib.sha256(data).hexdigest() if data is not None else None


def current(path):
    if path.is_symlink():
        raise ValueError(f'Refusing linked file: {path}')
    if path.exists() and not path.is_file():
        raise ValueError(f'Not a regular file: {path}')
    return path.read_bytes() if path.exists() else None


def target(workspace, relative):
    if relative not in ALLOWED:
        raise ValueError('Unknown adoption target in recovery record')
    path = workspace/relative
    # Check every ancestor touched by the operation, including an existing
    # skill directory symlink. Never write through a curated workspace link.
    stop = workspace.parent
    cursor = path.parent
    while cursor != stop:
        if cursor.is_symlink():
            raise ValueError(f'Refusing linked directory: {cursor}')
        cursor = cursor.parent
    return path


def update_persona(old):
    text = old.decode('utf-8')
    block = START + '\n' + border.JEV_ADVISOR_SECTION.rstrip() + '\n' + END
    if START in text or END in text:
        if text.count(START) != 1 or text.count(END) != 1 or text.index(END) < text.index(START):
            raise ValueError('Malformed Jev markers; existing persona retained')
        return (text[:text.index(START)] + block + text[text.index(END)+len(END):]).encode()
    # A workspace generated by spec125 already carries this exact section.
    # Put markers around that section without touching the rest of its persona.
    section = border.JEV_ADVISOR_SECTION.rstrip()
    if section in text:
        if text.count(section) != 1:
            raise ValueError('Multiple unmarked Jev sections; review manually')
        return text.replace(section, block, 1).encode()
    if '## Optional Science Officer' in text:
        raise ValueError('Unmarked custom Science Officer section; review before adoption')
    return (text + ('\n' if text.endswith('\n') else '\n\n') + block + '\n').encode()


def planned_changes(workspace):
    soul = target(workspace, 'SOUL.md')
    old = current(soul)
    if old is None:
        raise ValueError('Existing Border SOUL.md required; this helper does not bootstrap a RISK')
    desired = {'SOUL.md': update_persona(old)}
    for name in SKILLS:
        desired[f'skills/{name}/SKILL.md'] = (ROOT/'workspace/skills'/name/'SKILL.md').read_bytes()
    desired['../docs/JEV-SCIENCE-OFFICER.md'] = (ROOT/'docs/JEV-SCIENCE-OFFICER.md').read_bytes()
    # SOUL's docs/ link is workspace-relative; the skills' ../../../docs link
    # resolves beside the workspace. Support both without changing old backups.
    desired['docs/JEV-SCIENCE-OFFICER.md'] = desired['../docs/JEV-SCIENCE-OFFICER.md']
    changes = []
    for relative, after in desired.items():
        path = workspace/relative
        # Existing links to the shipped content need no writes. Preserve them.
        if path.is_file() and path.read_bytes() == after:
            continue
        path = target(workspace, relative)
        before = current(path)
        if before != after:
            changes.append({'path': relative, 'before': before, 'after': after,
                            'mode': stat.S_IMODE(path.stat().st_mode) if before is not None else None})
    return changes


def preview(changes):
    for change in changes:
        print(''.join(difflib.unified_diff(
            (change['before'] or b'').decode().splitlines(keepends=True),
            change['after'].decode().splitlines(keepends=True),
            fromfile=change['path'], tofile=change['path']+' (Jev adoption)', n=0)), end='')
    print(f'\n{len(changes)} files would change. Identity, members, other skills and MCP config are preserved.')


def apply(workspace, changes):
    if not changes:
        print('Already adopted; no files changed.')
        return
    for item in changes:
        if current(target(workspace, item['path'])) != item['before']:
            raise ValueError('Workspace changed after planning; rerun preview')
    directory = workspace/'.jev-adoption-backups'
    if directory.is_symlink():
        raise ValueError('Refusing linked recovery directory')
    directory.mkdir(mode=0o700, exist_ok=True)
    os.chmod(directory, 0o700)
    backup = directory/(datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')+'-'+uuid.uuid4().hex+'.json')
    record = {'version': 1, 'workspace': str(workspace), 'files': [
        {'path': item['path'], 'before_b64': base64.b64encode(item['before']).decode() if item['before'] is not None else None,
         'after_sha256': digest(item['after']), 'mode': item['mode']} for item in changes]}
    writer.write_private(backup, json.dumps(record, indent=2)+'\n')
    print(f'Recovery record: {backup}')
    for item in changes:
        writer.write_private(target(workspace, item['path']), item['after'].decode())
    print(f'Applied {len(changes)} scoped updates. Reload the Border to pick up its new instructions.')


def restore(workspace, backup):
    if backup.is_symlink():
        raise ValueError('Refusing linked recovery record')
    record = json.loads(backup.read_text())
    if record.get('version') != 1 or record.get('workspace') != str(workspace):
        raise ValueError('Recovery record belongs to a different workspace or version')
    rows = record['files']
    if not isinstance(rows, list) or len({row['path'] for row in rows}) != len(rows):
        raise ValueError('Invalid recovery target list')
    originals = []
    for row in rows:
        path = target(workspace, row['path'])
        original = base64.b64decode(row['before_b64'], validate=True) if row['before_b64'] is not None else None
        originals.append((path, original, row.get('mode')))
        if digest(current(path)) != row['after_sha256']:
            raise ValueError(f'Restore conflict: {row["path"]} changed after adoption; no files restored')
    for path, original, mode in originals:
        if original is None:
            path.unlink()
        else:
            writer.write_private(path, original.decode())
            if isinstance(mode, int):
                os.chmod(path, mode & 0o777)
    print(f'Restored {len(rows)} files; recovery record retained. Other workspace content was untouched.')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workspace', required=True, type=Path)
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--apply', action='store_true')
    group.add_argument('--restore', type=Path, metavar='RECOVERY_JSON')
    args = parser.parse_args(argv)
    workspace = args.workspace.expanduser().absolute()
    try:
        if workspace.is_symlink() or not workspace.is_dir():
            raise ValueError('Workspace must be an existing regular directory, not a symlink')
        if args.restore:
            restore(workspace, args.restore.expanduser())
        else:
            changes = planned_changes(workspace)
            if args.apply:
                apply(workspace, changes)
            else:
                preview(changes)
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f'Jev workspace adoption refused: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
